spring:
  application:
    name: rest-example
  datasource:
    url : jdbc:mysql://mysql-container:3306/usersDB?useSSL=false
    username : patryk
    password : 01Dom21!
# Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto : update